name: Solidot Robot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
        CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
      run: |
        env
        npm i
        npm test