name: Solidot Robot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4.1.0
      name: Install pnpm
      id: pnpm-install
      with:
        version: 9
        run_install: true

    - name: Test
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        CONSUMERKEY: ${{ secrets.CONSUMERKEY }}
        CONSUMERSECRET: ${{ secrets.CONSUMERSECRET }}
      run: |
        env
        pnpm test