name: cron

on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  triggers:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - run: date -u -d "+8 hour" && curl -XGET -L https://solibot.vercel.app/api/start
